#!/usr/bin/env bash
#this Bash script that displays To infinity and beyond indefinitely
#there is a Sleep 2 In between each iteration of the loop,

while true;
do
 echo "To infinity and beyond"
 sleep 2
done
