#!/usr/bin/env bash
#this script  displays numbers from 1 to 20 using while loop

count=1
while [ $count -le 20 ]
do
 echo "$count"
 case $count in
  "4") echo "bad luch from china";;
  "9") echo "bad luck from japan";;
  "17") echo "bad luck from italy";;
 esac
 (( count++))
done
